name: CI - Check

on:
  pull_request:
    branches:
      - main

jobs:
  ci-check:
    name: ci-check
    runs-on: [self-hosted, solinas]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build project
        run: mvn clean install -B
