name: CI – Generate Models & Annotations, Build ORD-Java

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Generate & Build ORD-Java
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout ord-maven repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '22'
          cache-dependency-path: tools/annotation-gen/package-lock.json

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 17
          maven-version: 3.9.14
          java-distribution: temurin

      - name: Build project
        run: mvn clean install -B -Dgpg.skip=true

      - name: Create or update pull request for generated sources
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: generated-sources
          commit-message: update generated annotations & models
          title: update generated annotations & models
          body: |
            This PR automatically updates the generated annotations and models in the folders:
            - models/src/main/java
            - annotations/src/main/java
            - annotations/src/main/resources

            Changes are automatically pushed to 'generated-sources' by the CI workflow on main.
          base: main
          add-paths: |
            models/**
            annotations/src/main/java/**
            annotations/src/main/resources/**
          token: ${{ secrets.GH_TOKEN }}
          delete-branch: false

      - name: Enable GitHub Auto-Merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash