name: CI – Generate Models & Annotations, Build ORD-Java

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Generate & Build ORD-Java
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ord-maven repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 22
          cache-dependency-path: tools/annotation-gen/package-lock.json

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 17
          maven-version: 3.9.14

      - name: Build project
        run: mvn clean install -B -Dgpg.skip=true

      - name: List files changed
        run: echo "CHANGED_FILES=$(git status -s)" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        if: env.CHANGED_FILES != ''
        run: awk '/^## \[\[[0-9].[0-9].[0-9]\]/{++i == 1 && gsub(/^/,"Update generated annotations and models\n\n")}1' CHANGELOG.md > tmp && mv tmp CHANGELOG.md

      - name: Update generated sources
        if: env.CHANGED_FILES != ''
        uses: devops-infra/action-commit-push@v1.1.0
        with:
          target_branch: main
          commit_prefix: "[AUTO]"
          github_token: "${{ secrets.GH_TOKEN }}"
          commit_message: "Update Open Resource Discovery generated annotations and models"

      - name: Trigger release workflow
        if: env.CHANGED_FILES != ''
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          repo: ord-maven
          owner: open-resource-discovery
          workflow_file_name: release.yml
          github_token: ${{ secrets.GH_TOKEN }}
