name: CI – Generate Models & Annotations, Build ORD-Java

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Generate & Build ORD-Java
    runs-on: [self-hosted, solinas]
    permissions:
      contents: write

    steps:
      - name: Checkout ord-maven repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Checkout ORD-Spec repo
        uses: actions/checkout@v3
        with:
          repository: CentralEngineering/open-resource-discovery-specification
          ref: feat/optional-annotation-fields
          path: ord-spec

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ord-spec/package-lock.json
      
      - name: Ensure sed is installed
        run: |
          if ! command -v sed &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y sed
          fi

      - name: Install ORD-Spec npm dependencies
        run: npm ci
        working-directory: ord-spec

      - name: Generate ORD schemas
        run: npm run generate
        working-directory: ord-spec

      - name: Generate Java Annotation Interfaces
        working-directory: ord-spec
        run: |
          mkdir -p ../java/annotations/target/generated-sources
          npx ts-node src/helper/generateJavaAnnotations.ts \
            --outDir ../java/annotations/target/generated-sources

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Maven manually
        run: |
          MAVEN_VERSION=3.9.6
          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$PWD/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$PWD/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Create annotations/pom.xml
        run: |
          cat > annotations/pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>

            <parent>
               <groupId>com.sap.ord</groupId>
               <artifactId>annotations</artifactId>
               <version>1.0.1</version>
            </parent>

            <artifactId>ord-annotations</artifactId>
            <name>ORD Annotations</name>

            <properties>
              <maven.compiler.source>1.8</maven.compiler.source>
              <maven.compiler.target>1.8</maven.compiler.target>
            </properties>

            <build>
              <sourceDirectory>src/main/java</sourceDirectory>

              <plugins>
               <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
              </plugin>

               <plugin>
                  <groupId>org.codehaus.mojo</groupId>
                  <artifactId>build-helper-maven-plugin</artifactId>
                  <version>3.4.0</version>
                  <executions>
                    <execution>
                      <id>add-generated-sources</id>
                      <phase>generate-sources</phase>
                      <goals>
                        <goal>add-source</goal>
                      </goals>
                      <configuration>
                        <sources>
                          <source>${project.basedir}/target/generated-sources</source>
                        </sources>
                      </configuration>
                    </execution>
                  </executions>
                </plugin>
              </plugins>
            </build>
          </project>
          EOF

      - name: Copy Document.schema.json into models folder
        run: |
          mkdir -p models/static/spec-v1/interfaces
          cp ord-spec/static/spec-v1/interfaces/Document.schema.json models/static/spec-v1/interfaces/

      - name: Create models/pom.xml
        run: |
          cat > models/pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                                       http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>

            <parent>
              <groupId>com.sap.ord</groupId>
              <artifactId>annotations</artifactId>
              <version>1.0.1</version>
            </parent>

            <artifactId>ord-models</artifactId>
            <name>ORD Java Models</name>

             <properties>
              <maven.compiler.source>1.8</maven.compiler.source>
              <maven.compiler.target>1.8</maven.compiler.target>
            </properties>

            <dependencies>
              <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.17.0</version>
              </dependency>
               <dependency>
                <groupId>com.sap.ord</groupId>
                <artifactId>ord-service</artifactId>
                <version>1.0.1</version>
              </dependency>
            </dependencies>

            <build>
              <resources>
                <resource>
                  <directory>${project.basedir}/static/spec-v1/interfaces</directory>
                  <includes>
                    <include>Document.schema.json</include>
                  </includes>
                  <targetPath>schemas</targetPath>
                </resource>
              </resources>

            <plugins>
                <!-- 1. JSON schema -> POJO directly in src/main/java -->
                <plugin>
                    <groupId>org.jsonschema2pojo</groupId>
                    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                    <version>1.2.2</version>
                    <executions>
                        <execution>
                            <id>generate-models</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <sourceDirectory>${project.basedir}/static/spec-v1/interfaces</sourceDirectory>
                        <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
                        <targetPackage>com.sap.ord.model</targetPackage>
                        <generateBuilders>true</generateBuilders>
                        <removeOldOutput>true</removeOldOutput>
                    </configuration>
                </plugin>
      
                <!-- 2. Patch all generated POJOs to implements PartialOrdPojo -->
                <plugin>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>3.1.0</version>
                    <executions>
                        <execution>
                            <id>patch-partial-interface</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>run</goal>
                            </goals>
                            <configuration>
                                <target>
                                    <replaceregexp byline="true" flags="g">
                                        <!-- all generated POJOs -->
                                        <fileset dir="${project.basedir}/src/main/java/com/sap/ord/model">
                                            <include name="**/*.java"/>
                                        </fileset>
                                        <!-- Search pattern -->
                                        <regexp pattern="public class ([A-Za-z0-9_]+) \{" />
                                        <!-- Inserting the interface -->
                                        <substitution expression="public class \1 implements com.sap.ord.service.hooks.PartialOrdPojo {" />
                                    </replaceregexp>
                                </target>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
      
                <!-- 3. Java-Compiler -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                    </configuration>
                </plugin>
            </plugins>
            </build>
          </project>
          EOF

      - name: Build project
        run: mvn clean install -B

      - name: List generated annotation files
        run: ls -R ord-spec/java/annotations/target/generated-sources

      - name: List generated model files
        run: ls -R java/models/src/main/java

      - name: Copy annotations into root-level annotations folder
        run: |
          mkdir -p annotations/src/main/java
          cp -R ord-spec/java/annotations/target/generated-sources/* annotations/src/main/java

      - name: Copy models into root-level models folder
        run: |
          mkdir -p models/src/main/java
          cp -R java/models/src/main/java/* models/src/main/java/

      - name: Remove ord-spec and existing java folder
        run: |
          rm -rf ord-spec
          rm -rf java

      - name: Create or update pull request for generated sources
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: generated-sources
          commit-message: update generated annotations & models
          title: update generated annotations & models
          body: |
            This PR automatically updates the generated annotations and models in the folders:
            - annotations/src/main/java
            - models/src/main/java

            Changes are automatically pushed to 'generated-sources' by the CI workflow on main.
          base: main
          add-paths: |
            annotations/**
            models/**
          token: ${{ secrets.GH_AUTOMERGE_PAT }}
          delete-branch: false

      - name: Enable GitHub Auto-Merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_AUTOMERGE_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash