name: CI – Generate Models & Annotations, Build ORD-Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Generate & Build ORD-Java
    runs-on: [self-hosted, solinas]
    permissions:
      contents: write

    steps:
      - name: Checkout ord-maven repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Checkout ORD-Spec repo
        uses: actions/checkout@v3
        with:
          repository: CentralEngineering/open-resource-discovery-specification
          ref: main
          path: ord-spec

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ord-spec/package-lock.json

      - name: Install ORD-Spec npm dependencies
        run: npm ci
        working-directory: ord-spec

      - name: Generate ORD schemas
        run: npm run generate
        working-directory: ord-spec

      - name: Generate Java Annotation Interfaces
        working-directory: ord-spec
        run: |
          mkdir -p ../java/annotations/target/generated-sources
          npx ts-node src/helper/generateJavaAnnotations.ts \
            --outDir ../java/annotations/target/generated-sources

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Download jsonschema2pojo CLI
        run: |
          curl -L -o jsonschema2pojo.zip \
            https://github.com/joelittlejohn/jsonschema2pojo/releases/download/jsonschema2pojo-1.2.2/jsonschema2pojo-1.2.2.zip
          unzip jsonschema2pojo.zip -d jsonschema2pojo

      - name: Generate Java POJOs from JSON Schema
        run: |
          mkdir -p java/models/src/main/java
          java -jar jsonschema2pojo/jsonschema2pojo-1.2.2/lib/jsonschema2pojo-cli-1.2.2.jar \
            --source ord-spec/static/spec-v1/interfaces/Document.schema.json \
            --target java/models/src/main/java \
            --package com.github.openresourcediscovery.model \
            --generate-constructors \
            --generate-builders

      - name: List generated annotation files
        run: ls -R ord-spec/java/annotations/target/generated-sources

      - name: List generated model files
        run: ls -R java/models/src/main/java

      - name: Copy annotations into repo root
        run: |
          mkdir -p java/annotations/target/generated-sources
          cp -R ord-spec/java/annotations/target/generated-sources/* java/annotations/target/generated-sources/

      - name: Remove ord-spec folder
        run: rm -rf ord-spec

      - name: Create new branch for generated files
        run: |
          git checkout -b feat/add-generated-sources

      - name: Commit all generated annotations and models
        run: |
          git add java/annotations/target/generated-sources
          git add java/models/src/main/java
          git add .
          git commit -m "chore(ci): add generated annotations & models, remove ord-spec"

      - name: Push new branch to origin
        run: git push -u origin feat/add-generated-sources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
