name: Deploy Java Package on Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (z. B. rel/1.2.3)'
        required: true
        type: string
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy tagged version to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.event.release.tag_name || github.ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Deploy with Maven
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
