name: "GitHub Release"

on:
  workflow_dispatch:
    inputs:
      models:
        description: "Publish `ord-models`"
        required: false
        type: boolean
        default: true
      annotations:
        description: "Publish `ord-annotations`"
        required: false
        type: boolean
        default: true
      githubRelease:
        description: "GitHub Release"
        required: false
        type: boolean
        default: true
      nextVersion:
        description: "Next Version"
        required: false
        type: string

jobs:
  create-release:
    environment: maven-central
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 17
          maven-version: 3.9.14
          settings-servers: '[{"id": "central", "username": "${{ secrets.MAVEN_CENTRAL_USER }}", "password": "${{ secrets.MAVEN_CENTRAL_PASSWORD }}"}]'

      - name: Extract version from pom.xml
        env:
          NEXT_VERSION: ${{ inputs.nextVersion }}
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null | sed 's/-SNAPSHOT$//')

          echo "CURRENT_VERSION=${PROJECT_VERSION}" >> $GITHUB_ENV
          echo "NEXT_VERSION=${NEXT_VERSION:-$(cut -d. -f1 <<<"${PROJECT_VERSION}").$(( $(cut -d. -f2 <<<"${PROJECT_VERSION}") + 1 )).0}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: open-resource-discovery/github-release@main
        if: inputs.githubRelease
        with:
          tag-template: "v<version>"
          version: ${{ env.CURRENT_VERSION }}

      - name: Update project release version
        run: |
          git reset --hard
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion="${{ env.CURRENT_VERSION }}"

      - name: Configure GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          gpg_private_key: ${{ secrets.MAVEN_GPG_SECRET_KEY }}

      - name: Create Maven Central release for org.open-resource-discovery:ord-models
        if: inputs.models
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          mvn --batch-mode deploy -f models/pom.xml -Dgpg.keyname="${MAVEN_GPG_KEY}"

      - name: Create Maven Central release for org.open-resource-discovery:ord-annotations
        if: inputs.annotations
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          mvn --batch-mode deploy -f annotations/pom.xml -Dgpg.keyname="${MAVEN_GPG_KEY}"

      - name: Update project version for next development iteration
        run: |
          git reset --hard
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion="${{ env.NEXT_VERSION }}-SNAPSHOT" 

      - name: Create pull request for project version
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          delete-branch: true
          token: ${{ secrets.GH_TOKEN }}
          branch: update-version-${{ env.NEXT_VERSION }}-SNAPSHOT
          title: Update project version to ${{ env.NEXT_VERSION }}-SNAPSHOT
          commit-message: Update project version to ${{ env.NEXT_VERSION }}-SNAPSHOT
          body: This PR automatically updates the project version to ${{ env.NEXT_VERSION }}-SNAPSHOT
          add-paths: |
            pom.xml
            models/pom.xml
            annotations/pom.xml

      - name: Enable GitHub Auto-Merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          merge-method: squash
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
